# Generated by Django 5.2 on 2025-04-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenFoodFact',
            fields=[
                ('barcode', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('product_name', models.TextField(blank=True, null=True)),
                ('brands', models.TextField(blank=True, null=True)),
                ('brands_en', models.TextField(blank=True, null=True)),
                ('brands_tags', models.TextField(blank=True, null=True)),
                ('origins', models.TextField(blank=True, null=True)),
                ('origins_en', models.TextField(blank=True, null=True)),
                ('origins_tags', models.TextField(blank=True, null=True)),
                ('countries', models.TextField(blank=True, null=True)),
                ('countries_en', models.TextField(blank=True, null=True)),
                ('countries_tags', models.TextField(blank=True, null=True)),
                ('cities', models.TextField(blank=True, null=True)),
                ('cities_tags', models.TextField(blank=True, null=True)),
                ('manufacturing_places', models.TextField(blank=True, null=True)),
                ('manufacturing_places_tags', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Open Food Facts',
                'ordering': ['barcode'],
            },
        ),
    ]
